comment: false
branches:
  - 'master'
codecov:
  require_ci_to_pass: no
coverage:
  status:
    project:
      default:
        target: 80%    # the required coverage value
        threshold: 15%  # the leniency in hitting the target